### ISSUE TITLE
Does ignoring comments work in Python 3.2?

### ISSUE THREAD

**Issue by 5nizza** [dabeaz/ply#25]
Hi, 

Discarding comments by returning None seems does not work. If add:

```
def t_COMMENT(t):
    r'\#.*'
    pass
    # No return value. Token discarded
```

And run example from the documentation with Python3.2, we will get:

Traceback (most recent call last):
  File "./parsing/calc.py", line 115, in <module>
    yacc.parse(s)
  File "./parsing/ply/yacc.py", line 303, in parse
    return self.parseopt_notrack(input,lexer,debug,tracking,tokenfunc)
  File "./parsing/ply/yacc.py", line 1095, in parseopt_notrack
    tok = call_errorfunc(self.errorfunc, errtoken, self)
  File "./parsing/ply/yacc.py", line 196, in call_errorfunc
    r = errorfunc(token)
  File "./parsing/calc.py", line 106, in p_error
    print("Syntax error at '%s'" % t.value)
AttributeError: 'NoneType' object has no attribute 'value'

The same is true for simple '\n'. Ideas?

Thanks!

**Comment by Joshua195** [comment]
@5nizza For multilinea comments how can I do it? I have this but it does not work
t_ignore_multi_comment = r'/\*(.|\r|\n)*?\*[\n]*?/'

**Comment by yjjnls** [comment]
> @5nizza For multilinea comments how can I do it? I have this but it does not work
> t_ignore_multi_comment = r'/*(.|\r|\n)_?*[\n]_?/'

r'(/\*(.|\n)*?\*/)|(//.*)' 
@Joshua195
